name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: itzhoman
          outputs: dist/github-contribution-grid-snake.svg
          palette: |
            - background: "#000000" # Black background
            - snake: "#FF0000" # Red snake
            - dot_empty: "#000000" # Black empty dots
            - dot0: "#00FF00" # Light green
            - dot1: "#00CC00" # Medium green
            - dot2: "#009900" # Darker green
            - dot3: "#006600" # Very dark green
          color_snake: true # Make snake color vibrant
          mask_snake: true # Smooth movement

      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
