name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *" # اجرای خودکار هر روز
  workflow_dispatch: # اجرای دستی

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: itzhoman
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
