name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # هر روز ساعت ۰۰:۰۰ اجرا می‌شود
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate the snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: itzhoman
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
