name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake gif
        uses: Platane/snk@v3
        with:
          github_user_name: itzhoman
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Upload SVG
        uses: actions/upload-artifact@v4
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
